import type { Metadata } from "next";
import "./globals.css";
import { ThemeContextProvider } from "@/contexts/ThemeContext";
import ThemeRegistry from "@/theme/ThemeRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeContextProvider>
          <ThemeRegistry>
            {children}
          </ThemeRegistry>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
